//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystemAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibrarySystemDB : DbContext
    {
        public LibrarySystemDB()
            : base("name=LibrarySystemDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Book> Tbl_Book { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
    
        public virtual ObjectResult<GetAllBooks_Result> GetAllBooks(Nullable<int> categoryId, Nullable<int> parentCategoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var parentCategoryIdParameter = parentCategoryId.HasValue ?
                new ObjectParameter("ParentCategoryId", parentCategoryId) :
                new ObjectParameter("ParentCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllBooks_Result>("GetAllBooks", categoryIdParameter, parentCategoryIdParameter);
        }
    
        public virtual ObjectResult<Tbl_Book> Fn_Book(Nullable<int> categoryId, Nullable<int> parentCategoryId)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var parentCategoryIdParameter = parentCategoryId.HasValue ?
                new ObjectParameter("ParentCategoryId", parentCategoryId) :
                new ObjectParameter("ParentCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_Book>("Fn_Book", categoryIdParameter, parentCategoryIdParameter);
        }
    
        public virtual ObjectResult<Tbl_Book> Fn_Book(Nullable<int> categoryId, Nullable<int> parentCategoryId, MergeOption mergeOption)
        {
            var categoryIdParameter = categoryId.HasValue ?
                new ObjectParameter("CategoryId", categoryId) :
                new ObjectParameter("CategoryId", typeof(int));
    
            var parentCategoryIdParameter = parentCategoryId.HasValue ?
                new ObjectParameter("ParentCategoryId", parentCategoryId) :
                new ObjectParameter("ParentCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_Book>("Fn_Book", mergeOption, categoryIdParameter, parentCategoryIdParameter);
        }
    
        public virtual ObjectResult<GetAllParentCategory_Result> GetAllParentCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllParentCategory_Result>("GetAllParentCategory");
        }
    
        public virtual ObjectResult<GetAllSubCategoryByParentId_Result> GetAllSubCategoryByParentId(Nullable<int> parentCategoryId)
        {
            var parentCategoryIdParameter = parentCategoryId.HasValue ?
                new ObjectParameter("ParentCategoryId", parentCategoryId) :
                new ObjectParameter("ParentCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllSubCategoryByParentId_Result>("GetAllSubCategoryByParentId", parentCategoryIdParameter);
        }
    
        public virtual ObjectResult<Tbl_Category> Fn_Category()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_Category>("Fn_Category");
        }
    
        public virtual ObjectResult<Tbl_Category> Fn_Category(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_Category>("Fn_Category", mergeOption);
        }
    
        public virtual ObjectResult<Tbl_Category> Fn_Category2(Nullable<int> parentCategoryId)
        {
            var parentCategoryIdParameter = parentCategoryId.HasValue ?
                new ObjectParameter("ParentCategoryId", parentCategoryId) :
                new ObjectParameter("ParentCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_Category>("Fn_Category2", parentCategoryIdParameter);
        }
    
        public virtual ObjectResult<Tbl_Category> Fn_Category2(Nullable<int> parentCategoryId, MergeOption mergeOption)
        {
            var parentCategoryIdParameter = parentCategoryId.HasValue ?
                new ObjectParameter("ParentCategoryId", parentCategoryId) :
                new ObjectParameter("ParentCategoryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tbl_Category>("Fn_Category2", mergeOption, parentCategoryIdParameter);
        }
    }
}
