//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystemAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Book
    {
        public int BookId { get; set; }
        public string BookName { get; set; }
        public Nullable<int> AuthorId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string Publication { get; set; }
        public Nullable<int> NoOfCopies { get; set; }
        public string Description { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
        public virtual Tbl_Category Tbl_Category1 { get; set; }
    }
}
